{% set name = "wasmtime" %}
{% set version = "29.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/bytecodealliance/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 0b3e2823b5a9155764bd1a5cba2f0e9f3069c407a5c329cce1f58dde6e67cd9d

build:
  number: 0
  skip: True # [linux and (s390x or ppc64le)]
  skip: True  # [win and (rust_compiler == 'rust-gnu')]
  missing_dso_whitelist:
    - lib/libgcc_s.so.1
    - $RPATH/libpthread.so.0
    - $RPATH/libm.so.6
    - $RPATH/libdl.so.2
    - $RPATH/libc.so.6
    - /lib64/ld-linux-x86-64.so.2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cmake
    - make  # [linux]

  run:
    - libgcc-ng                  # [linux]

test:
  commands:
    - wasmtime --help
    - test -f ${PREFIX}/lib/libwasmtime.so      # [linux]
    - test -f ${PREFIX}/lib/libwasmtime.dylib   # [osx]
    - if not exist %PREFIX%\Library\bin\wasmtime.dll exit 1    # [win]
    - if not exist %PREFIX%\Library\lib\wasmtime.dll.lib exit 1    # [win]

about:
  home: https://github.com/bytecodealliance/wasmtime
  summary: A WebAssembly runtime powered by Wasmtime
  description: |
   Wasmtime is a Bytecode Alliance project that is a standalone wasm-only optimizing runtime for WebAssembly and WASI. 
   It runs WebAssembly code outside of the Web, and can be used both as a command-line utility 
   or as a library embedded in a larger application.
  license_family: Apache
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.wasmtime.dev/
  dev_url: https://github.com/bytecodealliance/wasmtime

extra:
  recipe-maintainers:
    - markw77
